### PR TITLE
tell jetpack that buttons when dragged should offer to uninstall addon.

### PR DESCRIPTION
**Pull request by gregglind**

### CODE REVIEW

**Comment by raymak** [comment]
I think there are 2 levels of moving:

1- moving to the burger menu: which I think is fine and means that they don't want their toolbar to be busy
2- moving to the customize area: which I think means I don't want this tool, but am not worried about privacy and such: I think we can just silence the notification for this. Alternatively we can uninstall it silently.

**Comment by gregglind** [comment]
The customize area seems weirdly hard to catch, fwiw :)  For reasons I don't grok.  Try it using that simpler addon.

**Comment by raymak** [comment]
the browser.uiCustomization.state has some relevant stuff.

**Comment by gregglind** [comment]
I claim this is superceded and closed.

**Comment by raymak** [comment]
superceded by #282

**Pull request closed without merging**
